version: "3.7"

services:
  user_api:
    container_name: user_api
    image: user_api
    restart: always
    environment:
      - API_DEBUG=${DEBUG}
      - API_PORT=${PORT}
      - API_OAUTH_APP_ID=${OAUTH_APP_ID}
      - API_OAUTH_APP_SECRET=${OAUTH_APP_SECRET}
    ports:
      - 3000:3000
  mysql:
    image: mysql:5.7.31
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - .env 
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - /data/mysql:/var/lib/mysql
      - /data/dump:/docker-entrypoint-initdb.d/dump.sql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8085:80"
    env_file:
      - .env 
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306