version: "3.7"

services:
  user_api:
    container_name: user_api
    image: user_api
    restart: always
    depends_on:
      - postgres
    environment:
      - API_DEBUG=TRUE
      - API_PORT=3000
      - API_USERNAME=postgres
      - API_PASSWORD=password
      - API_HOST=localhost:5432
      - API_NAME=user_api
    ports:
      - "3000:3000"
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres-bdd:/var/lib/postgresql/data
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - "8085:8080"
    depends_on:
      - postgres

volumes:
  postgres-bdd:
    name: postgres-bdd