version: "3.7"

networks:
  api:
    name: api
    external: false

services:
  api:
    container_name: api
    image: api
    restart: always
    depends_on:
      - postgres
    environment:
      - API_DEBUG=TRUE
      - API_PORT=3000
      - API_USERNAME=postgres
      - API_PASSWORD=password
      - API_HOST=postgres
      - API_NAME=user_api
    networks:
      - api
    ports:
      - "3000:3000"
  postgres:
    container_name: postgres
    image: timescale/timescaledb:latest-pg14
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    networks:
      - api
    ports:
      - "5432:5432"
    volumes:
      - postgres-bdd:/var/lib/postgresql/data
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    networks:
      - api
    ports:
      - "8085:8080"
    depends_on:
      - postgres

volumes:
  postgres-bdd:
    name: postgres-bdd
