version: "3.7"

services:
  user_api:
    container_name: user_api
    image: user_api
    restart: always
    depends_on:
      - postgres
    environment:
      - API_DEBUG=${DEBUG}
      - API_PORT=${PORT}
      - API_OAUTH_APP_ID=${OAUTH_APP_ID}
      - API_OAUTH_APP_SECRET=${OAUTH_APP_SECRET}
      - API_USERNAME=${POSTGRES_USERNAME}
      - API_PASSWORD=${POSTGRES_PASSWORD}
      - API_HOST=${POSTGRES_HOST}
      - API_NAME=${POSTGRES_DBNAME}
    ports:
      - "3000:3000"
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-bdd:/var/lib/postgresql/data
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - "8085:8080"
    depends_on:
      - postgres

volumes:
  postgres-bdd:
    name: postgres-bdd